### ISSUE TITLE
DUG #4 roadmaps don't align with GH milestones

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/presentations#34]
Fix errors in the DUG roadmaps:
- [ ]  MSI release versions:
- [MSI Z690-A v1.2.0](https://github.com/Dasharo/presentations/blob/main/dasharo_roadmap.md#dasharo-desktop-msi-z690-a-roadmap) vs v1.4.1 in https://github.com/Dasharo/dasharo-issues/milestone/12
- [MSI Z790-P v1.0.0](https://github.com/Dasharo/presentations/blob/main/dasharo_roadmap.md#dasharo-desktop-msi-z790-p-roadmap) vs v0.9.2 in https://github.com/Dasharo/dasharo-issues/milestone/12
- [ ] MSI Z690-A Dasharo (coreboot+Heads) v0.9.0 milestone
 -  In a presentation, it is mentioned as Z790-P instead of [MSI Z690-A Dasharo (coreboot+Heads) v0.9.0](https://github.com/Dasharo/dasharo-issues/milestone/22)

**Comment by pietrushnic** [comment]
@BeataZdunczyk 

- v1.1.4 has yet to deliver a delivery date.
- v0.9.2 a/a

If you say that community releases are the same as v1.4.1 and v0.9.2, then you do not respect [release versioning convention name](https://docs.dasharo.com/dev-proc/versioning/). If those are not community releases but DES releases, that is fine. Let's also create milestones for community releases so those can be reflected in the Dasharo Roadmap presentation.

> In a presentation, it is mentioned as Z790-P instead of [MSI Z690-A Dasharo (coreboot+Heads) v0.9.0](https://github.com/Dasharo/dasharo-issues/milestone/22)

I think both Z790-P and Z690-A should get the Dasharo (coreboot+Heads) release, mainly because the Z690-A hardwire is harder and harder to get.

**Comment by BeataZdunczyk** [comment]
@pietrushnic Okay, understood. So, separate GitHub milestones are needed for community releases.

> I think both Z790-P and Z690-A should get the Dasharo (coreboot+Heads) release

That sounds good. We are releasing Dasharo (coreboot+Heads) for both boards for DES, so it makes sense (_which was not the case when I wrote this issue, initially, we had only planned release for Z690 boards_).

**Comment by pietrushnic** [comment]
Fixed: da30d4e87938

I'm closing this issue since this is the way I will present DUG#5. In case of further issues, please let me know through bug against DUG#6.
